amcl:
  ros__parameters:
    use_sim_time: true
    use_tf: true
    base_frame_id: "base_footprint"
    odom_frame_id: "odom"
    scan_topic: "/scan"
    odom_topic: "/odom"
    particlecloud_topic: "particlecloud"
    min_particles: 500
    max_particles: 2000
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    laser_max_range: 30.0
    resample_interval: 1
    
map_server:
  ros__parameters:
    map: "/home/mrc/sim_ws/src/particle_filter/map/my_map.yaml"
